#pragma once
//NOLINTBEGIN

/******************************
 * Operating system detection
 ******************************/
#define DRR_PLATFORM_OS_UNKNOWN 0u
#define DRR_PLATFORM_OS_WIN32 1u << 0u /**< Microsoft Windows (32-bit) */
#define DRR_PLATFORM_OS_WIN64 1u << 1u /**< Microsoft Windows (64-bit) */
#define DRR_PLATFORM_OS_CYGWIN 1u << 2u /**< Cygwin */
#define DRR_PLATFORM_OS_WINDOWS (DRR_PLATFORM_OS_WIN32 | DRR_PLATFORM_OS_WIN64 | DRR_PLATFORM_OS_CYGWIN) /**< Microsoft Windows */
#define DRR_PLATFORM_OS_POSIX 1u << 3u /**< POSIX */

#ifdef _WIN32
#ifdef _WIN64
#define DRR_PLATFORM_OS_HAS_WIN64 DRR_PLATFORM_OS_WIN64
#else
#define DRR_PLATFORM_OS_HAS_WIN32 DRR_PLATFORM_OS_WIN32
#endif//WIN64
#endif//WIN32
#ifdef __CYGWIN__
#define DRR_PLATFORM_OS_HAS_CYGWIN DRR_PLATFORM_OS_CYGWIN
#endif//CYGWIN
#ifndef DRR_PLATFORM_OS_HAS_WIN32
#define DRR_PLATFORM_OS_HAS_WIN32 DRR_PLATFORM_OS_UNKNOWN
#endif
#ifndef DRR_PLATFORM_OS_HAS_WIN64
#define DRR_PLATFORM_OS_HAS_WIN64 DRR_PLATFORM_OS_UNKNOWN
#endif
#ifndef DRR_PLATFORM_OS_HAS_CYGWIN
#define DRR_PLATFORM_OS_HAS_CYGWIN DRR_PLATFORM_OS_UNKNOWN
#endif

#define DRR_PLATFORM_OS_HAS_WINDOWS (DRR_PLATFORM_OS_HAS_WIN32 | DRR_PLATFORM_OS_HAS_WIN64 | DRR_PLATFORM_OS_HAS_CYGWIN)

#ifdef _POSIX_VERSION
#define DRR_PLATFORM_OS_HAS_POSIX DRR_PLATFORM_OS_POSIX
#endif//POSIX
#ifndef DRR_PLATFORM_OS_HAS_POSIX
#define DRR_PLATFORM_OS_HAS_POSIX DRR_PLATFORM_OS_UNKNOWN
#endif

#define DRR_PLATFORM_OS (DRR_PLATFORM_OS_HAS_WINDOWS | DRR_PLATFORM_OS_HAS_POSIX)

//NOLINTEND